In [1]:
import numpy as np

In [2]:
#scalar array
A=np.array(5)
A

array(5)

In [3]:
np.ndim(A)#dimension

0

In [4]:
One=np.array([1,2,3,4,5])
np.ndim(One)

1

In [5]:
One

array([1, 2, 3, 4, 5])

In [6]:
Two=np.array([[1,2,3],[4,5,6]])
Two

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.ndim(Two)

2

In [8]:
Three=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
Three

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [9]:
np.ndim(Three)

3

In [10]:
#list-different datatypes
#array-similar datatypes

In [11]:
arr=np.array([1,2,3,4,5])
list1=[1,2.3,'akshay']

In [12]:
arr=np.array([1,2,3.9,'apple']) 
#type conversion occurs here and all elements are converted to strings.

In [13]:
type(arr)

numpy.ndarray

In [14]:
arr

array(['1', '2', '3.9', 'apple'], dtype='<U32')

In [15]:
#numpy allows mathematical operations.
arr=np.array([1,2,3,4,5])
arr/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [16]:
#list/5 will give error.

In [17]:
#advantages of numpy array over list.
#array consumes less memory.
#array are faster than lists.

In [19]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3) #1d to 2d array.

In [20]:
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
newarr=arr.reshape(2,3,2)
print(newarr)
#1D to 3D array

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [23]:
arr=np.array([1,2,3,4])
print(arr[1])

2


In [24]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])#1st row 2nd elem

2


In [25]:
print(arr[1,4])#2nd row 5th elem

10


In [26]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2]) #0th matrix 2nd row 3rd column

6


In [27]:
print(arr[1,1,0]) #1st matrix,2nd row,1st column

10


In [28]:
a1=np.array([1,2,3,4,5,6,7])
a1[1:5]

array([2, 3, 4, 5])

In [30]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2[1,1:4]    #[row:column]

array([7, 8, 9])

In [31]:
a2[0:2,2]

array([3, 8])

In [32]:
a2[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [33]:
a3=np.array([[[10,11,12],[13,14,15],[16,17,18]],
             [[20,21,22],[23,24,25],[26,27,28]],
             [[30,31,32],[33,34,35],[36,37,38]]])

In [35]:
a3[:2,1:,:2]   #[matrix:row:column]

array([[[13, 14],
        [16, 17]],

       [[23, 24],
        [26, 27]]])

In [36]:
a3.shape

(3, 3, 3)

In [37]:
#VIEW AND COPY
#COPY IS A NEW ARRAY.
#VIEW IS JUST A VIEW OF ORIGINAL ARRAY.
#ANY CHANGES MADE TO THE COPY WILL NOT AFFECT THE ORIGINAL ARRAY.
#ANY CHANGES MADE TO THE VIEW WILL AFFECT THE ORIGINAL ARRAY.

In [38]:
arr=np.array([1,2,3,4,5])
copy=arr.copy()
copy[0]=42
print(arr)
print(copy)

[1 2 3 4 5]
[42  2  3  4  5]


In [39]:
view=arr.view()
view[0]=42
print(arr)
print(view)

[42  2  3  4  5]
[42  2  3  4  5]


In [40]:
a=np.array([[1,2,3],[4,5,6]])
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.append(a,[[7,8,9]],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
np.append(a,[[5],[8]],axis=1)

array([[1, 2, 3, 5],
       [4, 5, 6, 8]])

In [43]:
a=np.array([[1,2],[3,4],[5,6]])
np.insert(a,3,[11,12])

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [45]:
np.insert(a,1,[11,12],axis=0)

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

In [47]:
np.insert(a,1,[11,12,13],axis=1)

array([[ 1, 11,  2],
       [ 3, 12,  4],
       [ 5, 13,  6]])

In [48]:
a=np.array([[1,2,3,12],
            [9,5,6,11],
            [8,4,10,7]])
np.delete(a,9)

array([ 1,  2,  3, 12,  9,  5,  6, 11,  8, 10,  7])

In [49]:
np.delete(a,1,axis=1)

array([[ 1,  3, 12],
       [ 9,  6, 11],
       [ 8, 10,  7]])

In [50]:
np.delete(a,1,axis=0)

array([[ 1,  2,  3, 12],
       [ 8,  4, 10,  7]])

In [51]:
np.ndim(a)

2

In [52]:
#Hstack AND Vstack
#HSTACK IS USED TO JOIN 2 ARRAYS HORIZONTALLY.
#VSTACK IS USED TO JOIN 2 ARRAYS VERICALLY. 

In [53]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a,b)

[1 2 3] [4 5 6]


In [54]:
print(np.ndim(a),np.ndim(b))

1 1


In [55]:
#HSTACK
result=np.hstack((a,b))
print(result,np.ndim(result))

[1 2 3 4 5 6] 1


In [56]:
#VSTACK
result=np.vstack((a,b))
print(result,np.ndim(result))

[[1 2 3]
 [4 5 6]] 2


In [57]:
#NUMPY CONCATENATION-- USED FOR JOINING 2 OR MORE ARRAYS
#OF SAME SHAPE ALONG A SPECIFIED AXIS.
#AXIS=0 => ADDING NEW ROWS.
#AXIS=1 => ADDING NEW COLUMNS.

In [58]:
arr1=np.array([[2,4],[6,8]])
arr2=np.array([[3,5],[7,9]])
arr3=np.array([[3],[9]])
arr4=np.array([[4,8]])
new=np.concatenate((arr1,arr2),axis=0)

In [59]:
new

array([[2, 4],
       [6, 8],
       [3, 5],
       [7, 9]])

In [60]:
new=np.concatenate((arr1,arr2),axis=1)
new

array([[2, 4, 3, 5],
       [6, 8, 7, 9]])

In [61]:
import pandas as pd
series=pd.Series([1,7,2,8,5])
print(series)

0    1
1    7
2    2
3    8
4    5
dtype: int64


In [62]:
series=pd.Series([1,7,2,8,5],index=["a","b","c","d","e"])

In [63]:
print(series)

a    1
b    7
c    2
d    8
e    5
dtype: int64


In [64]:
print(series["a"])

1


In [65]:
data=pd.DataFrame([1,2,3,4,5])
data

0
0  1
1  2
2  3
3  4
4  5

In [69]:
data=pd.DataFrame({'Name':['a','b','c','d'],'Age':[23,34,56,78]})
data.head()

Name  Age
0    a   23
1    b   34
2    c   56
3    d   78

In [74]:
data=pd.DataFrame({'Name':['a','b','c','d'],'Age':[23,34,56,78]},index=['x','y','z','w'])
data.head()

Name  Age
x    a   23
y    b   34
z    c   56
w    d   78

In [75]:
data['Name']

x    a
y    b
z    c
w    d
Name: Name, dtype: object

In [76]:
data.loc['x','Name']

'a'

In [77]:
#in loc taking label values.

In [79]:
data.iloc[2,0]

'c'

In [80]:
#gives output corresponding to 2nd label and 0th column/attribute.

In [81]:
data.iloc[3,1]

78

In [82]:
#pandas concatenation - to concatenate objects along a particular
#axis with optional set logic along other axis.
names=pd.DataFrame({'name':['a','b','c','d']})
age=pd.DataFrame({'age':[12,23,34,45]})
names2=pd.DataFrame({'name':['e','f','h','i']})

In [83]:
names

name
0    a
1    b
2    c
3    d

In [85]:
pd.concat([names,age],axis=1)

name  age
0    a   12
1    b   23
2    c   34
3    d   45

In [86]:
pd.concat([names,names2],axis=0)

name
0    a
1    b
2    c
3    d
0    e
1    f
2    h
3    i

In [87]:
data=pd.DataFrame({'Name':['a','b','c','d'],'Age':[23,34,56,78]},index=['x','y','z','w'])
data.head()

Name  Age
x    a   23
y    b   34
z    c   56
w    d   78

In [88]:
data[data['Age']<50][['Name']]

Name
x    a
y    b

In [89]:
data.loc['x','Age']

23

In [91]:
data.iloc[2,1]

56